In [5]:
import numpy as np
import copy
import time

def person_position(P_1):
    
    # search the position of player
    for i in range(len(P_1)): #length
        for j in range(len(P_1[0])): #width
            if P_1[i][j] == 2:
                return ([i,j])

def Trans_array_str(P):
    a = ''
    for i in range(len(P)):
        for j in range(len(P[0])):
            a += str(P[i][j])
    return a

def is_OK(P_1,P_end):
    ## check if current state match final state
    for i in range(len(P_1)):
        if P_1[i] !='3' and P_end[i] =='4':
            return False   # 没推到位置
    return True # 所有的坐标，3都在相应end4的位置

def best_move(pathfinal):
    moves = ''
    for i in range(len(pathfinal)):
        if pathfinal[i]==[0,-1]:
            moves+='L'
        if pathfinal[i]==[-1,0]:
            moves+='U'
        if pathfinal[i]==[0,1]:
            moves+="R"
        if pathfinal[i]==[1,0]:
            moves+='D'
    return moves

In [19]:
P=np.array([[0,0,0,0,0,0,0,0],[0,4,1,0,1,1,1,0],[0,1,1,3,1,1,1,0],[0,1,1,1,0,1,0,0],[0,0,1,0,1,3,4,0],[0,1,1,1,3,1,1,0],[0,1,1,4,0,1,2,0],[0,0,0,0,0,0,0,0]])
print(P)

dirs=[[0,-1],[-1,0],[0,1],[1,0]]## four directions 'L''U''R''D'

length_r = P.shape[0]
length_c = P.shape[1]
print(length_r)
print(length_c)

a = Trans_array_str(P)
print(a)

P_transform = a.replace('4','1')
print(P_transform)

P_end = a.replace('2','1')
P_end = P_end.replace('3','1')
print(P_end)

states=[] ## frontier, record states to explore
iterate_max=1000 ## death loop maximum
person=person_position(P)

visited = [P_transform] ## record visited states

pathfinal=[]
print('-------------')


states=[[P_transform,[],person]]

while(len(states)>0):
        
    #print(len(states))
    P = states[0][0]  ##initial status
    path = states[0][1]
    person = states[0][2] 

    if len(path)>iterate_max:                                 ##deal with too long loop
        break
        
    if is_OK(P,P_end):   # 所有箱子都推到位，返回true；否则，返回false
        if len(pathfinal)==0:
            pathfinal=path
            continue                                                ##check if ok
        elif len(path)<len(pathfinal):
            pathfinal=path
            continue
            
    states=states[1:]  ##explore the current status,update the frontier

    
    for i,dir in enumerate(dirs):
        neg=[person[0]+dir[0],person[1]+dir[1]]##the neighbour
        #print(neg)
        nneg=[person[0]+2*dir[0],person[1]+2*dir[1]]   ##the neighbour of the neighbour
        #print(nneg)    
            #if not (neg[0]>=0 and neg[0]<len(P) and neg[1]>=0 and neg[1]<len(P[0])):
        if not ( neg[0]>0 and neg[0]<(length_r-1) and neg[1]>0 and neg[1]<(length_c-1) ):
            continue     # 触碰边界
        #print('ssss')
        #print(P[neg[0]*length_c + neg[1] ])
        if P[ neg[0]*length_c + neg[1] ]==str(1):           ## only the person move
            Pnew_1 = P[0:(neg[0]*length_c + neg[1] )] + '2' + P[(neg[0]*length_c + neg[1] +1):]

            Pnew_2 = Pnew_1[0:(person[0]*length_c + person[1] ) ] + '1' + Pnew_1[(person[0]*length_c + person[1] +1):]
                #Pnew[person[0]][person[1]]=1 # 移动一步，更新地图
            #print('Pnew_2')
            #print(Pnew_2)  
            if Pnew_2 not in visited:## check if visited
                visited.append(Pnew_2)
                    
                states.append([Pnew_2,path+[dir],neg])  ##add new status in frontier
                    
        elif P[neg[0]*length_c + neg[1] ]==str(3) and P[nneg[0]*length_c + nneg[1] ]==str(1):
                #Pnew_1 = ''
            Pnew_1 = P[0:(neg[0]*length_c + neg[1] )] + '2' + P[(neg[0]*length_c + neg[1] +1):]
            Pnew_2 = Pnew_1[0:(person[0]*length_c + person[1] ) ] + '1' + Pnew_1[(person[0]*length_c + person[1] +1):]
            Pnew_3 = Pnew_2[0:(nneg[0]*length_c + nneg[1] ) ] + '3' + Pnew_2[(nneg[0]*length_c + nneg[1] +1):]
            if Pnew_3 not in visited:                                            ## check if visited
                visited.append(Pnew_3)
                    
                states.append([Pnew_3,path+[dir],neg])  ##add new status in frontier
        #print(pathfinal)
print(best_move(pathfinal))

[[0 0 0 0 0 0 0 0]
 [0 4 1 0 1 1 1 0]
 [0 1 1 3 1 1 1 0]
 [0 1 1 1 0 1 0 0]
 [0 0 1 0 1 3 4 0]
 [0 1 1 1 3 1 1 0]
 [0 1 1 4 0 1 2 0]
 [0 0 0 0 0 0 0 0]]
8
8
0000000004101110011311100111010000101340011131100114012000000000
0000000001101110011311100111010000101310011131100111012000000000
0000000004101110011111100111010000101140011111100114011000000000
-------------
LULLRURUULLLDLURDDDLDR
