In [589]:
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 25 22:20:00 2019

@author: byjiang
"""

'''
easiest pushing box

0: boundary and wall
1: path can be moved
2: player
3: box
4: storage
5: box is put in the position of storage (box+storage)
6: person is put in the position of storage (person+storage)


Known
[[0 0 0 0 0 0]
 [0 4 3 1 2 0]
 [0 0 0 0 0 0]]

result
[[0 0 0 0 0 0]
 [0 5 2 1 1 0]
 [0 0 0 0 0 0]]

'''

'\neasiest pushing box\n\n0: boundary and wall\n1: path can be moved\n2: player\n3: box\n4: storage\n5: box is put in the position of storage (box+storage)\n6: person is put in the position of storage (person+storage)\n\n\nKnown\n[[0 0 0 0 0 0]\n [0 4 3 1 2 0]\n [0 0 0 0 0 0]]\n\nresult\n[[0 0 0 0 0 0]\n [0 5 2 1 1 0]\n [0 0 0 0 0 0]]\n\n'

In [590]:
import numpy as np

In [591]:
def person_position(P_1):
    
    # search the position of player
    
    for i in range(len(P_1)): #length
        for j in range(len(P_1[0])): #width
            if P_1[i][j] == 2 or P_1[i][j] == 6:
                return ([i,j])

def box_position(P_1):
    
    # search the position of box
    box = []
    for i in range(len(P_1)):
        for j in range(len(P_1[0])):
            if P_1[i][j] == 3:
                box.append([i,j])
    return (box)


def target_position(P_1):
    
    # search the position of box
    target = []
    for i in range(len(P_1)):
        for j in range(len(P_1[0])):
            if P_1[i][j] == 4:
                target.append([i,j])
    return (target)

def explore_path(person): # person (x,y)
    # explore the path that the player can move
    moving_position = []
    for i in range(person[0]-1,person[0]+2):
        for j in range(person[1]-1,person[1]+2):
            if P_1[i][j] == 1 or P_1[i][j] == 3: # Next step can be a box or a clearing
                moving_position.append([i,j])
    return moving_position

def block_judgement(P_1):
    

In [592]:
boxes = []
person = []
targets = []
moving_position = []

def process(P_1):
    
    boxes = box_position(P_1)
    person = person_position(P_1)
    targets = target_position(P_1)
    moving_position = explore_path(person)#  something like [[1,2],[1,3]]
    
    if len(moving_position) == 0:
        return (P_1)
    if P_1[person[0]][person[1]] == 2:    
        for i in range(len(moving_position)):
            if (P_1[moving_position[i][0]][moving_position[i][1]] == 1): #不涉及推箱子
                    P_1[moving_position[i][0]][moving_position[i][1]] = 2
                    P_1[person[0]][person[1]] = 1
                    return (P_1)
            if (P_1[moving_position[i][0]][moving_position[i][1]] == 4): #不涉及推箱子
                    P_1[moving_position[i][0]][moving_position[i][1]] = 6 
                    P_1[person[0]][person[1]] = 1
                    return (P_1)
            if P_1[moving_position[i][0]][moving_position[i][1]] == 3:
                a = moving_position[i][0] - person[0]
                b = moving_position[i][1] - person[1]
                if (P_1[moving_position[i][0]+a][moving_position[i][1]+b] == 4): # can move the box
                    P_1[moving_position[i][0]+a][moving_position[i][1]+b] = 5
                    P_1[moving_position[i][0]][moving_position[i][1]] = 2
                    P_1[person[0]][person[1]] = 1
                    return(P_1)
                
                if (P_1[moving_position[i][0]+a][moving_position[i][1]+b] == 1): # can move the box
                    P_1[moving_position[i][0]+a][moving_position[i][1]+b] = 3
                    P_1[moving_position[i][0]][moving_position[i][1]] = 2
                    P_1[person[0]][person[1]] = 1
                    return(P_1)
                else:# can not move the box
                    moving_position.pop(i)
                    if len(moving_position) == 0:
                        return(P_1)
            
            if P_1[moving_position[i][0]][moving_position[i][1]] == 5:
                a = moving_position[i][0] - person[0]
                b = moving_position[i][1] - person[1]
                if (P_1[moving_position[i][0]+a][moving_position[i][1]+b] == 4): # can move the box
                    P_1[moving_position[i][0]+a][moving_position[i][1]+b] = 5
                    P_1[moving_position[i][0]][moving_position[i][1]] = 6
                    P_1[person[0]][person[1]] = 1
                    return(P_1)
                
                if (P_1[moving_position[i][0]+a][moving_position[i][1]+b] == 1): # can move the box
                    P_1[moving_position[i][0]+a][moving_position[i][1]+b] = 3
                    P_1[moving_position[i][0]][moving_position[i][1]] = 6
                    P_1[person[0]][person[1]] = 1
                    return(P_1)
                else: #can not move the box
                    moving_position.pop(i)
                    if len(moving_position) == 0:
                        return(P_1)
                    
    if P_1[person[0]][person[1]] == 6:
        for i in range(len(moving_position)):
            if (P_1[moving_position[i][0]][moving_position[i][1]] == 1): #不涉及推箱子
                    P_1[moving_position[i][0]][moving_position[i][1]] = 2
                    P_1[person[0]][person[1]] = 4
                    return (P_1)
            if (P_1[moving_position[i][0]][moving_position[i][1]] == 4): #不涉及推箱子
                    P_1[moving_position[i][0]][moving_position[i][1]] = 6 
                    P_1[person[0]][person[1]] = 4
                    return (P_1)
            if P_1[moving_position[i][0]][moving_position[i][1]] == 3: 
                a = moving_position[i][0] - person[0]
                b = moving_position[i][1] - person[1]
                if (P_1[moving_position[i][0]+a][moving_position[i][1]+b] == 4): # can move the box
                    P_1[moving_position[i][0]+a][moving_position[i][1]+b] = 5
                    P_1[moving_position[i][0]][moving_position[i][1]] = 2
                    P_1[person[0]][person[1]] = 4
                    return(P_1)
                
                if (P_1[moving_position[i][0]+a][moving_position[i][1]+b] == 1): # can move the box
                    P_1[moving_position[i][0]+a][moving_position[i][1]+b] = 3
                    P_1[moving_position[i][0]][moving_position[i][1]] = 2
                    P_1[person[0]][person[1]] = 4
                    return(P_1)
                else:# can not move the box
                    moving_position.pop(i)
                    if len(moving_position) == 0:
                        return(P_1)
            
            if P_1[moving_position[i][0]][moving_position[i][1]] == 5:
                a = moving_position[i][0] - person[0]
                b = moving_position[i][1] - person[1]
                if (P_1[moving_position[i][0]+a][moving_position[i][1]+b] == 4): # can move the box
                    P_1[moving_position[i][0]+a][moving_position[i][1]+b] = 5
                    P_1[moving_position[i][0]][moving_position[i][1]] = 6
                    P_1[person[0]][person[1]] = 4
                    return(P_1)
                
                if (P_1[moving_position[i][0]+a][moving_position[i][1]+b] == 1): # can move the box
                    P_1[moving_position[i][0]+a][moving_position[i][1]+b] = 3
                    P_1[moving_position[i][0]][moving_position[i][1]] = 6
                    P_1[person[0]][person[1]] = 4
                    return(P_1)
                else: #can not move the box
                    moving_position.pop(i)
                    if len(moving_position) == 0:
                        return(P_1)

In [593]:
P = [[0,0,0,0,0,0],[0,4,3,1,2,0],[0,0,0,0,0,0]]
for n in range(3):
    print(P)
    P = process(P)
    

[[0, 0, 0, 0, 0, 0], [0, 4, 3, 1, 2, 0], [0, 0, 0, 0, 0, 0]]
[[0, 0, 0, 0, 0, 0], [0, 4, 3, 2, 1, 0], [0, 0, 0, 0, 0, 0]]
[[0, 0, 0, 0, 0, 0], [0, 5, 2, 1, 1, 0], [0, 0, 0, 0, 0, 0]]


In [594]:
# ------------------------------ to be continued ------------------

P = [[0,0,0,0,0,0],[0,4,3,1,2,0],[0,0,0,0,0,0]]
num_cal = 10
person_records = [] 
Q = []
for n in range(num_cal):
    person_records.append(person_position(P))
    Q = P
    P = process(P)
    if ((Q == P).all()):
        person_records.pop(len(person_records)-1)
        break
        if len(person_records) == 0:
            break
    else:
        for i in range(P_1.shape[0]):
            for j in range(P_1.shape[1]):
                if (P_1[i][j] == 2) or (P_1[i][j] == 6):
                    person_records.append(P_1[i][j])
    if not(4 in P_1):
        print(person_records,n)
        break
        
            
# print(person_records)  
    

AttributeError: 'bool' object has no attribute 'all'

In [ ]:
P_1 = np.array([[0,0,0,0,1,0],[0,4,3,1,2,0],[0,0,0,0,0,0]])
P_2 = np.array([[0,0,0,0,1,0],[0,4,3,1,2,0],[0,0,0,0,0,0]])
if (P_1 == P_2).all():
    print(1)
else:
    print(0)
    
c = 8 in P_1
c

In [ ]:
u = 10
i = 8
if not(u == i):
    print(1)